export default [
    {id:1, url:'./images/bg1.jpg'},
    {id:2, url:'./images/bg2.jpg'},
    {id:3, url:'./images/bg3.jpg'},
    {id:4, url:'./images/bg4.jpg'},
    {id:5, url:'./images/bg5.jpg'},
    {id:6, url:'./images/bg6.jpg'},
    {id:7, url:'./images/bg7.jpg'},
    {id:8, url:'./images/bg8.jpg'},
    {id:9, url:'./images/bg9.jpg'},
    {id:10, url:'./images/bg10.jpg'},
    {id:11, url:'./images/bg11.jpg'},
    {id:12, url:'./images/bg12.jpg'},
    {id:13, url:'./images/bg13.jpg'},
    {id:14, url:'./images/bg14.jpg'},
    {id:15, url:'./images/bg15.jpg'},
    {id:16, url:'./images/bg16.jpg'},
    {id:17, url:'./images/bg17.jpg'},
    {id:18, url:'./images/bg18.jpg'},
    {id:19, url:'./images/bg19.jpg'},
    {id:20, url:'./images/bg20.jpg'},
]